/**
 * CLI: provision the three Parley wallets.
 *
 * Default path is local EVM keypairs, because that is what `GatewayClient`
 * actually authenticates with (docs/x402-sdk-verified-surface.md). Pass
 * --stub to get deterministic fake addresses instead, for a machine where no
 * keys should exist at all.
 *
 * Private keys are written to `.env.local.generated` and nowhere else. That
 * file is gitignored. Keys are never printed to stdout, because terminal
 * scrollback ends up in screen recordings.
 *
 * Usage: pnpm provision-wallets [--stub]
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ARC_TESTNET_CAIP2,
  ARC_TESTNET_FAUCET_URL,
  loadConfigFromEnv,
} from "@parley/shared";
import { LocalKeyWalletProvider } from "./local-key-wallet-provider.js";
import { StubWalletProvider } from "./stub-wallet-provider.js";
import type { WalletRole } from "./wallet-provider-interface.js";

const ADDRESS_ENV_BY_ROLE: Record<WalletRole, string> = {
  buyer: "BUYER_WALLET_ADDRESS",
  seller: "SELLER_WALLET_ADDRESS",
  "seller-payout": "SELLER_PAYOUT_WALLET_ADDRESS",
};

const PRIVATE_KEY_ENV_BY_ROLE: Record<WalletRole, string> = {
  buyer: "BUYER_PRIVATE_KEY",
  seller: "SELLER_PRIVATE_KEY",
  "seller-payout": "SELLER_PAYOUT_PRIVATE_KEY",
};

async function provisionStubWallets(): Promise<void> {
  console.warn(
    [
      "",
      "==================== STUB WALLETS ====================",
      " These addresses are FABRICATED. They cannot receive",
      " faucet USDC and cannot settle anything. Drop --stub",
      " to generate real Arc Testnet keypairs.",
      "======================================================",
      "",
    ].join("\n"),
  );

  const wallets = await new StubWalletProvider().provisionAll();
  for (const wallet of wallets) {
    console.log(`  ${wallet.role.padEnd(14)} ${wallet.address}  [STUB]`);
  }
}

async function provisionLocalKeyWallets(): Promise<void> {
  const config = loadConfigFromEnv();
  const provider = new LocalKeyWalletProvider({
    existingKeys: {
      buyer: config.buyerPrivateKey,
      seller: config.sellerPrivateKey,
      "seller-payout": config.sellerPayoutPrivateKey,
    },
  });

  const wallets = await provider.provisionAll();
  const reused = provider.reusedAllExistingKeys;

  console.log(
    `provider: ${provider.name}  network: ${ARC_TESTNET_CAIP2}` +
      (reused ? "  (reused existing keys from .env)" : "  (generated fresh keys)"),
  );
  for (const wallet of wallets) {
    console.log(`  ${wallet.role.padEnd(14)} ${wallet.address}`);
  }

  const lines = provider.revealKeypairsForEnvFile().flatMap((keypair) => [
    `${ADDRESS_ENV_BY_ROLE[keypair.role]}=${keypair.address}`,
    `${PRIVATE_KEY_ENV_BY_ROLE[keypair.role]}=${keypair.privateKey}`,
  ]);

  const outputPath = resolve(process.cwd(), ".env.local.generated");
  writeFileSync(
    outputPath,
    [
      "# Generated by `pnpm provision-wallets`.",
      "# CONTAINS PRIVATE KEYS. Gitignored. Arc TESTNET only.",
      "# Copy into .env, then delete this file.",
      ...lines,
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`\nwrote ${outputPath}  (contains private keys, gitignored)`);
  console.log(
    `\nNext:` +
      `\n  1. Copy the contents into .env, then delete .env.local.generated.` +
      `\n  2. Fund each address at ${ARC_TESTNET_FAUCET_URL} (select Arc Testnet).` +
      `\n     Roughly 20 USDC per request, once every 2 hours, per address.` +
      `\n  3. The buyer wallet also needs a Gateway deposit before it can pay.`,
  );
}

async function main(): Promise<void> {
  if (process.argv.includes("--stub")) {
    await provisionStubWallets();
    return;
  }
  await provisionLocalKeyWallets();
}

main().catch((error: unknown) => {
  // Never print a raw error object: an SDK error can echo key material back
  // inside its request context.
  const message = error instanceof Error ? error.message : String(error);
  console.error(`provision-wallets failed: ${message}`);
  process.exitCode = 1;
});
